# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

vars:
    # dbt run --vars '{"dapl_raw_db": "DAPL_RAW_PRD_DB"}'
    var_raw_prd: RAW_PRD
    var_raw_dev: RAW_DEV
    var_raw_qas: RAW_QAS

models:
  jaffle_shop:
    marts:
        core:
          #materialized: table
          +database: DEMO_DB
          +schema: MART 
      # Applies to all files under models/example/
    staging:
      materialized: view
      +database: DEMO_DB
      +schema: STAGING 

#snapshots:
    ##+target_database: generate_database_name(DEMO_DB)
    ##+target_schema: generate_schema_name(MART)    